version: "3"

services:
  retrogaming.api:
    container_name: retrogaming.api
    image: node
    ports:
      - "4000:3000"
    env_file:
      - ./api/.env.dev
    volumes:
      - ./api:/usr/src/app
      - ./api/node_modules:/usr/src/outside/node_modules
    working_dir: /usr/src/app
    command: bash -c 'npm i && npm run dev'